### ISSUE TITLE
score

### ISSUE THREAD

**Issue by 0nce1** [bonsaistudios/lexvision#7]
score calc

**Comment by Jauchi** [comment]
Mittelwert aus ALLEN Attributen als variable bereitstellen.
Ampel der DB hinzufügen.

**Comment by Jauchi** [comment]
PROBLEM:
Das Score Attribute wird beim erstellen eines Objects aus der DB *nicht* als letztes gesettet, d.h. es müsste nach dem erstellen nochmal aktualisiert werden. Ich mach morgen weiter :c

**Comment by Jauchi** [comment]
implemented and fixed
